default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: makersbnb_development

test: &test
  <<: *default
  database: makersbnb_test

production:
  <<: *default
  database: mydb
