
development:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_test
  pool: 5
